version: '3'
services:
    web:
      build:
        context: .
      ports:
        - 8080:8080
      depends_on: 
        - redis
      volumes:
        - ".:/app"
    redis:
      image: "redis:alpine"
      ports:
        - "6379:6379"