version: '3'
services:
    web:
      build: .
      ports:
        - "8080:8081"
      depends_on: 
        - redis
      volumes:
        - ".:/app"
    redis:
      image: "redis:alpine"
      ports:
        - "6379:6379"